/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.views.PatientView;
import core.views.DoctorView;
import core.views.AdminView;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.UIManager;
import core.models.Administrator;
import core.controllers.Appointment;
import core.models.Doctor;
import core.controllers.Hospitalization;
import core.models.Patient;
import core.models.User;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class LoginView extends javax.swing.JFrame {

    private int x, y;
    private ArrayList<User> users;
    private ArrayList<Hospitalization> hospitalizations;
    private ArrayList<Appointment> appointments;

    public LoginView() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        this.users = new ArrayList<>();
        this.users.add(new Administrator(0, "admin", "admin", "adnim", "admin123"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new core.controllers.PanelRound();
        panelRound2 = new core.controllers.PanelRound();
        Close_Button = new javax.swing.JButton();
        Main_screen_tabs = new javax.swing.JTabbedPane();
        Login_tab = new core.controllers.PanelRound();
        Login_label = new javax.swing.JLabel();
        Enter_username_field = new javax.swing.JTextField();
        Username_label = new javax.swing.JLabel();
        Enter_password_field = new javax.swing.JTextField();
        Password_label = new javax.swing.JLabel();
        Enter_button = new javax.swing.JButton();
        Patient_registration_tab = new javax.swing.JPanel();
        Firstname_label = new javax.swing.JLabel();
        Firstname_field = new javax.swing.JTextField();
        Lastname_label = new javax.swing.JLabel();
        Lastname_field = new javax.swing.JTextField();
        ID_label = new javax.swing.JLabel();
        ID_field = new javax.swing.JTextField();
        Gender_Label = new javax.swing.JLabel();
        Phone_Label = new javax.swing.JLabel();
        Phone_Field = new javax.swing.JTextField();
        Email_Label = new javax.swing.JLabel();
        Email_Field = new javax.swing.JTextField();
        PatientReg_User_Label = new javax.swing.JLabel();
        PatientReg_User_Field = new javax.swing.JTextField();
        PatientReg_Password_Field = new javax.swing.JTextField();
        PatientReg_Password_Label = new javax.swing.JLabel();
        PatientReg_Password_Confirmation_Label = new javax.swing.JLabel();
        PatientReg_Password_Confirmation_Field = new javax.swing.JTextField();
        Gender_dropdowm = new javax.swing.JComboBox<>();
        PatientReg_Save_Button = new javax.swing.JButton();
        Address_Label = new javax.swing.JLabel();
        Address_Field = new javax.swing.JTextField();
        Birthdate_Label = new javax.swing.JLabel();
        Birthdate_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setRadius(50);

        panelRound2.setRadius(50);
        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        Close_Button.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Close_Button.setText("X");
        Close_Button.setBorderPainted(false);
        Close_Button.setContentAreaFilled(false);
        Close_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Close_Button.setFocusable(false);
        Close_Button.setRequestFocusEnabled(false);
        Close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close_Button)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Login_label.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Login_label.setText("LOGIN");

        Enter_username_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Enter_username_field.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Username_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Username_label.setText("USERNAME");

        Enter_password_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Enter_password_field.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Password_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Password_label.setText("PASSWORD");

        Enter_button.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Enter_button.setText("ENTER");
        Enter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Login_tabLayout = new javax.swing.GroupLayout(Login_tab);
        Login_tab.setLayout(Login_tabLayout);
        Login_tabLayout.setHorizontalGroup(
            Login_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Login_tabLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(Login_label)
                .addGap(481, 481, 481))
            .addGroup(Login_tabLayout.createSequentialGroup()
                .addGroup(Login_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Login_tabLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(Login_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Login_tabLayout.createSequentialGroup()
                                .addGroup(Login_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password_label, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Username_label, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Login_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Enter_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Enter_username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Login_tabLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(Enter_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Login_tabLayout.setVerticalGroup(
            Login_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_tabLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Login_label)
                .addGap(74, 74, 74)
                .addComponent(Username_label)
                .addGap(18, 18, 18)
                .addComponent(Enter_username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password_label)
                .addGap(18, 18, 18)
                .addComponent(Enter_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Enter_button)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        Main_screen_tabs.addTab("Login", Login_tab);

        Firstname_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Firstname_label.setText("Firstname");

        Firstname_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        Lastname_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Lastname_label.setText("Lastname");

        Lastname_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        ID_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        ID_label.setText("ID");

        ID_field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        Gender_Label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Gender_Label.setText("Gender");

        Phone_Label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Phone_Label.setText("Phone");

        Phone_Field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        Email_Label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Email_Label.setText("Email");

        Email_Field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PatientReg_User_Label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientReg_User_Label.setText("User");

        PatientReg_User_Field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PatientReg_Password_Field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        PatientReg_Password_Label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientReg_Password_Label.setText("Password");

        PatientReg_Password_Confirmation_Label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientReg_Password_Confirmation_Label.setText("Password confirmation");

        PatientReg_Password_Confirmation_Field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientReg_Password_Confirmation_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientReg_Password_Confirmation_FieldActionPerformed(evt);
            }
        });

        Gender_dropdowm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Gender_dropdowm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        PatientReg_Save_Button.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        PatientReg_Save_Button.setText("Save");
        PatientReg_Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientReg_Save_ButtonActionPerformed(evt);
            }
        });

        Address_Label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Address_Label.setText("Address");

        Address_Field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        Birthdate_Label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Birthdate_Label.setText("Birthdate");

        Birthdate_Field.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout Patient_registration_tabLayout = new javax.swing.GroupLayout(Patient_registration_tab);
        Patient_registration_tab.setLayout(Patient_registration_tabLayout);
        Patient_registration_tabLayout.setHorizontalGroup(
            Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                .addGroup(Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(PatientReg_Password_Label))
                    .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatientReg_User_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientReg_Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(PatientReg_User_Label))
                    .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(PatientReg_Password_Confirmation_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(PatientReg_Save_Button))
                    .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(PatientReg_Password_Confirmation_Label))
                    .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                                .addComponent(Birthdate_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Birthdate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                                .addComponent(Firstname_label)
                                .addGap(34, 34, 34)
                                .addComponent(Firstname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lastname_label)
                            .addComponent(Address_Label))
                        .addGap(18, 18, 18)
                        .addGroup(Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                                .addComponent(Lastname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ID_label)
                                .addGap(30, 30, 30)
                                .addComponent(ID_field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Gender_Label)
                                .addGap(26, 26, 26)
                                .addComponent(Gender_dropdowm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                                .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Phone_Label)
                                .addGap(18, 18, 18)
                                .addComponent(Phone_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Email_Label)
                                .addGap(18, 18, 18)
                                .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        Patient_registration_tabLayout.setVerticalGroup(
            Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Patient_registration_tabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Firstname_label)
                    .addComponent(Firstname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lastname_label)
                    .addComponent(Lastname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_label)
                    .addComponent(ID_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender_Label)
                    .addComponent(Gender_dropdowm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Birthdate_Label)
                        .addComponent(Birthdate_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Address_Label)
                        .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Phone_Label)
                        .addComponent(Phone_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Patient_registration_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Email_Label)
                        .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(PatientReg_User_Label)
                .addGap(18, 18, 18)
                .addComponent(PatientReg_User_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientReg_Password_Label)
                .addGap(18, 18, 18)
                .addComponent(PatientReg_Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PatientReg_Password_Confirmation_Label)
                .addGap(18, 18, 18)
                .addComponent(PatientReg_Password_Confirmation_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(PatientReg_Save_Button)
                .addGap(42, 42, 42))
        );

        Main_screen_tabs.addTab("Patient register", Patient_registration_tab);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(Main_screen_tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main_screen_tabs)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Close_ButtonActionPerformed

    private void Enter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter_buttonActionPerformed
        // TODO add your handling code here:
        User selectedUser = null;
        for (User user : this.users) {
            if (Enter_username_field.getText().equals(user.getUsername())) {
                selectedUser = user;
                if (selectedUser.getPassword().equals(Enter_password_field.getText())) {
                    if (selectedUser instanceof Administrator ) {
                        AdminView admin = new AdminView(selectedUser,users,hospitalizations, appointments);
                        this.setVisible(false);
                        admin.setVisible(true);
                    }
                    else if (selectedUser instanceof Doctor ) {
                        DoctorView doctor = new DoctorView(selectedUser,(Doctor)selectedUser,users,hospitalizations,appointments);
                        this.setVisible(false);
                        doctor.setVisible(true);
                    }
                    else {
                        PatientView patient = new PatientView(selectedUser,(Patient) selectedUser,users,appointments, hospitalizations);
                        this.setVisible(false);
                        patient.setVisible(true);
                    }
                }
            }
        }

    }//GEN-LAST:event_Enter_buttonActionPerformed

    private void PatientReg_Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientReg_Save_ButtonActionPerformed
        String firstname = Firstname_field.getText();
        String lastname = Lastname_field.getText();
        long id = Long.parseLong(ID_field.getText());
        boolean gender = (Gender_dropdowm.getSelectedIndex() == 0 ? null : (Gender_dropdowm.getSelectedIndex() == 1 ));
        String birth = Birthdate_Field.getText();
        String address = Address_Field.getText();
        long phone = Long.parseLong(Phone_Field.getText());
        String email = Email_Field.getText();
        String user = PatientReg_User_Field.getText();
        String password = PatientReg_Password_Field.getText();
        String comPassword = PatientReg_Password_Confirmation_Field.getText();
        LocalDate birthdate = LocalDate.of(Integer.parseInt(birth.substring(0, 4)), Integer.parseInt(birth.substring(5, 7)), Integer.parseInt(birth.substring(8)));
        if (comPassword.equals(password)) {
            users.add(new Patient(id, user, firstname, lastname, password, email, birthdate, gender, phone, address));
        }
        
    }//GEN-LAST:event_PatientReg_Save_ButtonActionPerformed

    private void PatientReg_Password_Confirmation_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientReg_Password_Confirmation_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientReg_Password_Confirmation_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.setProperty("flatlaf.useNativeLibrary", "false");

        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address_Field;
    private javax.swing.JLabel Address_Label;
    private javax.swing.JTextField Birthdate_Field;
    private javax.swing.JLabel Birthdate_Label;
    private javax.swing.JButton Close_Button;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JButton Enter_button;
    private javax.swing.JTextField Enter_password_field;
    private javax.swing.JTextField Enter_username_field;
    private javax.swing.JTextField Firstname_field;
    private javax.swing.JLabel Firstname_label;
    private javax.swing.JLabel Gender_Label;
    private javax.swing.JComboBox<String> Gender_dropdowm;
    private javax.swing.JTextField ID_field;
    private javax.swing.JLabel ID_label;
    private javax.swing.JTextField Lastname_field;
    private javax.swing.JLabel Lastname_label;
    private javax.swing.JLabel Login_label;
    private core.controllers.PanelRound Login_tab;
    private javax.swing.JTabbedPane Main_screen_tabs;
    private javax.swing.JLabel Password_label;
    private javax.swing.JTextField PatientReg_Password_Confirmation_Field;
    private javax.swing.JLabel PatientReg_Password_Confirmation_Label;
    private javax.swing.JTextField PatientReg_Password_Field;
    private javax.swing.JLabel PatientReg_Password_Label;
    private javax.swing.JButton PatientReg_Save_Button;
    private javax.swing.JTextField PatientReg_User_Field;
    private javax.swing.JLabel PatientReg_User_Label;
    private javax.swing.JPanel Patient_registration_tab;
    private javax.swing.JTextField Phone_Field;
    private javax.swing.JLabel Phone_Label;
    private javax.swing.JLabel Username_label;
    private core.controllers.PanelRound panelRound1;
    private core.controllers.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
